version: 2
jobs:
   build:
     branches:
        ignore:
          - /deploy-.*/
     docker:
       - image: circleci/node:lts
     steps:
       - run: sudo apt-get install -y gawk
       - checkout
       - run: npm i
       - run: npm run check-types
       - run: npm run lint
       - run: npm run i18n:validatejs
       - run: npm run i18n:validate
       - run: npm test